apiVersion: v1
kind: ConfigMap
metadata:
  name: helpdesk-config
  namespace: helpdesk
data:
  S3_BUCKET_NAME: "helpdesk-attachments-yourname"   # <-- עדכן לשם ה-bucket האמיתי שלך
  AWS_REGION: "us-east-1"
  DB_DIR: "/data"
  FLASK_ENV: "production"
