apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: helpdesk-data-pvc
  namespace: helpdesk
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: gp2
