apiVersion: v1
kind: Service
metadata:
  name: helpdesk-service
  namespace: helpdesk
spec:
  selector:
    app: helpdesk-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer
